import './globals.css';
import { Inter } from 'next/font/google';

import Provider from '../recoil/provider1.js';

import Account from '@/assemblies/Account.js';
import Operators from '@/assemblies/Operators.js';

import ACCOUNT_MENU from '@/data/ACCOUNT_MENU.js';
import OPERATORS from '@/data/OPERATORS.js';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    const account_menu = ACCOUNT_MENU;
    const operators = OPERATORS;

    console.log('3--')

    return (
        <html lang="ja">
          <body className={inter.className}>
            <Provider>
              <Account menu={account_menu}/>
              <Operators operators={operators}/>

              {children}
            </Provider>
          </body>
        </html>
    );
}
